# Generated by Django 4.2.28 on 2026-02-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BubeleCareSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120)),
                ('family_code', models.CharField(max_length=40)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bubele Care site',
                'verbose_name_plural': 'Bubele Care sites',
                'ordering': ['site_name'],
            },
        ),
        migrations.CreateModel(
            name='ICBCSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('year_constructed', models.CharField(blank=True, max_length=16)),
                ('water_source', models.CharField(blank=True, max_length=255)),
                ('preschool_summary', models.CharField(blank=True, max_length=255)),
                ('projects', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('ploughing_season', models.CharField(blank=True, max_length=16)),
                ('hours_ploughed', models.CharField(blank=True, max_length=64)),
                ('families_ploughed_for', models.CharField(blank=True, max_length=128)),
                ('area_ploughed', models.CharField(blank=True, max_length=128)),
                ('site_link', models.URLField(blank=True)),
                ('photo_path', models.CharField(blank=True, help_text='Relative image path used for the panorama/cover image.', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo_path', models.CharField(blank=True, help_text='Relative pastor photo path.', max_length=255)),
                ('role', models.CharField(blank=True, default='Pastor', max_length=80)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pastor', to='icbc.icbcsite')),
            ],
        ),
    ]
