# Generated by Django 4.2.28 on 2026-02-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsWorkbookUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stats_workbooks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('skipped_duplicates', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='icbcsite',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Panoramic cover photo for this ICBC site.', null=True, upload_to='icbc_covers/'),
        ),
        migrations.AddField(
            model_name='pastor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Uploaded pastor portrait used on the ICBC page.', null=True, upload_to='pastors/'),
        ),
        migrations.AlterField(
            model_name='icbcsite',
            name='photo_path',
            field=models.CharField(blank=True, help_text='Relative image path used for the panorama/cover image (existing static assets).', max_length=255),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='photo_path',
            field=models.CharField(blank=True, help_text='Relative pastor photo path (existing static asset).', max_length=255),
        ),
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Optional photo for this update.', null=True, upload_to='icbc_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='icbc.icbcsite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icbc_sites/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='If checked, this image may be highlighted on the ICBC page.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='icbc.icbcsite')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=100)),
                ('total_attendance', models.IntegerField(default=0)),
                ('men', models.IntegerField(default=0)),
                ('women', models.IntegerField(default=0)),
                ('youth', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('salvations', models.IntegerField(default=0)),
                ('baptisms', models.IntegerField(default=0)),
                ('home_visits', models.IntegerField(default=0)),
                ('meals_food_packs', models.IntegerField(default=0)),
                ('preschool_attendance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='icbc.icbcsite')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
