# Generated by Django 4.2.28 on 2026-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icbc', '0002_statsworkbookupload_icbcsite_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icbcsite',
            name='maize_farmers_supported',
            field=models.PositiveIntegerField(default=0, help_text='Number of farmers supported through the maize buy-back programme.'),
        ),
        migrations.AddField(
            model_name='icbcsite',
            name='maize_tonnes_purchased',
            field=models.FloatField(default=0, help_text='Total tonnes of maize purchased so far for this ICBC.'),
        ),
    ]
