# Generated by Django 4.2.28 on 2026-02-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icbc', '0003_icbcsite_maize_farmers_supported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. Lead Teacher, Assistant Teacher', max_length=120)),
                ('photo', models.ImageField(blank=True, help_text='Portrait photo of this teacher.', null=True, upload_to='teachers/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='icbc.icbcsite')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompassionateCareMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. Coordinator, Volunteer', max_length=120)),
                ('photo', models.ImageField(blank=True, help_text='Portrait photo of this care team member.', null=True, upload_to='care_team/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='icbc.icbcsite')),
            ],
            options={
                'verbose_name': 'Compassionate care team member',
                'verbose_name_plural': 'Compassionate care team members',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
